# Generated by Django 5.0.1 on 2024-04-15 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
    ]
