# Generated by Django 5.0.1 on 2024-04-15 02:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=40, verbose_name='Nombre Proyecto')),
                ('project_description', models.TextField(verbose_name='Descripcion del proyecto')),
                ('proyect_objetive', models.TextField(verbose_name='Objetivo del proyecto')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Creado el ')),
                ('update_at', models.DateField(auto_now=True, verbose_name='Actualizado el')),
                ('project_owner', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='proyectos_creador', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Rol de Admin')),
                ('joined_at', models.DateField(auto_now=True, verbose_name='Unido el')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('proyect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos_miembros', to='proyects.proyect')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('completed', models.BooleanField(default=False, verbose_name='Completa')),
                ('important', models.BooleanField(default=False, verbose_name='Importancia de la tarea')),
                ('datecompleted', models.DateTimeField(blank=True, null=True, verbose_name='Completa el')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Creado el ')),
                ('update_at', models.DateField(auto_now=True, verbose_name='Actualizado el')),
                ('asigned_at', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas_asignadas', to='proyects.member')),
                ('proyect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='proyects.proyect')),
            ],
        ),
    ]
